name: pyOxygenStream Continuous Integration tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: 3.9
        cache: 'pip'
        cache-dependency-path: 'requirements.txt'
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Running unit tests
      run: python3 -m pytest .
